"""add  nationality

Revision ID: 5eaa5b300712
Revises: bd107f4d44d2
Create Date: 2025-11-29 10:56:41.381352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eaa5b300712'
down_revision: Union[str, None] = 'bd107f4d44d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('nationality', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'nationality')
    # ### end Alembic commands ###
