"""add genre to books

Revision ID: 718fc685276a
Revises: d02872a24078
Create Date: 2025-11-29 14:40:38.218975

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "718fc685276a"
down_revision: Union[str, None] = "d02872a24078"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("genre", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "genre")
    # ### end Alembic commands ###
